### ISSUE TITLE
[AndroidHomePage]-Android Uygulama İçin Giriş Sayfasının Geliştirilmesi

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#10]
Surveysaurus Android uygulamamız için kullanıcıyı karşılayacak olan sayfa.

- [x] Sayfanın üst barında orta kısımda uygulamanın logosu bulunmalıdır. 

- [x]  Sayfanın sağ üst köşesinde kullanıcının profil bilgilerine ulaşabileceği profil ikonu bulunmalıdır. Bu ikona tıklandığında açılır menü ile giriş yapılmış ise kullanıcı "User Info", "My surveys" ve "Log out" seçeneklerine ulaşabilmelidir. 

- [x] Sayfa başında ortalanmış bir şekilde uygulamanın logosu ve 'Surveysaurus' yazısı bulunmalıdır. Logo ve marka adının (Surveysaurus) altında 'Create your Survey Saurus for free' yazısı yazmalıdır.

- [x] 'Create your Survey Saurus for free'yazısının altında yine sayfayı ortalayacak şekilde anket oluşturma butonu olmalıdır.Buton üstünde 'Create Survey' yazısı yazmalıdır.  

- [x]  'Create Survey' butonunun altında kullanıcıyı, uygulamada var olan anket listesine nasıl ulaşabileceğine yönlendirecek olan 'Swipe To See Our Surveys' yazısı ile belirtilmelidir.

- [x]  Sayfanın sol üst kısmında üç çizik halinde ikon bulunmalı ve bu ikona basılabilmelidir. İkona basıldığında 'Home' 'Sign Up','Login' işlemleri çıkmalıdır.Kullanıcı giriş yapmış ise 'Sign In','Sign Up' işlemleri yerine '@username'
yazmalıdır.

**Comment by ummugulsumm** [comment]
## Test Senaryosu

### Ana sayfanın genel görüntüsünün incelenmesi

- **Test Adımları**

1. Anasayfadaki yazıların içeriği ve konumu kontrol edilmelidir.

- **Beklenen Sonuç**

1. Sayfa başında ortalanmış bir şekilde uygulamanın logosu ve 'Surveysaurus' yazısı bulunmalıdır. Logo ve marka adının (Surveysaurus) altında 'Create your Survey Saurus for free' yazısı yazmalıdır. Yazının altında sayfayı ortalayacak şekilde anket oluşturma butonu olmalıdır. Buton üstünde 'Create Survey' yazısı yazmalıdır. Butonunun altında 'Swipe To See Our Surveys' yazısı olmalıdır. 
 
### Ana sayfanın üst kısmının incelenmesi

- **Test Adımları**
 
1. Üst barın içeriği ve konumlanışı kontrol edilmelidir.

- **Beklenen Sonuç**

1. Sayfanın üst barında orta kısımda uygulamanın logosu bulunmalıdır. Sayfanın sağ üst köşesinde profil ikonu bulunmalıdır. Sayfanın sol üst kısmında üç çizik halinde ikon bulunmalı.

### Profil ikonunun incelenmesi

- **Test Adımları**

1. Profil ikonuna tıkla.
2. Başarılı bir şekilde giriş yap. 
3. Üst bardan profil ikonuna tıkla.

- **Beklenen Sonuç**

1. İkon tıklanılabilir olmalıdır.
2. Giriş yapılmalıdır.
3. Menü açılmalıdır. "User Info", "My surveys" ve "Log out" seçeneklerine ulaşılabilmelidir. 

### Üç çizgi ikonunun incelenmesi

- **Test Adımları**

1. Giriş yapmadan üç çizgi ikonuna tıkla. 
2. Başarılı bir şekilde giriş yap. 
3. Giriş yaptıktan sonra üç çizgi ikonuna tıkla.

- **Beklenen Sonuç**

1. 'Home' 'Sign Up','Login' işlemleri çıkmalıdır.
2. Giriş yapılmalıdır. 
3. Sign up ve Login kısımları kaybolmuş olmalıdır. Sign Up kısmı yerinde '@username'
yazmalıdır.
