### ISSUE TITLE
[UserProfile]-Kullanıcı Bilgilerini Görebileceği Sayfanın Geliştirilmesi

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#13]
Kullanıcı giriş yaptıktan sonra, kendine ait oluşturduğu anketleri görebileceği ve bilgilerini düzenleyebileceği bir sayfa olmalıdır.

- [x] Kullanıcı giriş yaptıktan sonra, üst bardaki karakter ikonuna tıkladığında açılır bir menü oluşmalıdır. 

- [x]  Açılır menüde bilgilerini görüntüleyebilme (User Info) ve oluşturmuş olduğu anketleri görebilme (My Surveys) seçenekleri olmalıdır.

- [x] #45
- [x] #33

**Comment by ummugulsumm** [comment]
## Test Senaryosu

### Profil ikonunun incelenmesi

- **Test Adımları**

1. Profil ikonuna tıkla.
2. Başarılı bir şekilde giriş yap. 
3. Üst bardan profil ikonuna tıkla.
4. "User Info" seçeneğine tıkla.
5. "My Surveys" seçeneğine tıkla. 

- **Beklenen Sonuç**

1. İkon tıklanılabilir olmalıdır.
2. Giriş yapılmalıdır.
3. Menü açılmalıdır. "User Info", "My surveys" ve "Log out" seçeneklerine ulaşılabilmelidir. 
4. Kullanıcı "User Info" kısmına tıkladığında kullanıcı bilgilerinin olduğu sayfaya yönlendirilmelidir.
5. Kullanıcı "My Surveys" kısmına tıkladığında oluşturmuş olduğu anketlerin listelendiği sayfaya yönlendirilmelidir.
