### ISSUE TITLE
[CommentSection]-Upvote ve Report Edildiğinde Belli Olmaması Problemi

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#138]
- [x] Kullanıcı bir yoruma upvote vermediği durumda upvote butonunun içi boş kalmalı ve yanında da upvote miktarı yazmalıdır.

- [x] Kullanıcı bir yoruma upvote vermiş ise upvote butonunun içi tasarımda bulunan renk kartelasındaki mavi renk ile boyanmış olmalıdır ve upvote miktarı güncellenmelidir.

- [x] Kullanıcı bir yorumu report etmiş ise report bayrağı kırmızı ile boyanmış olmalıdır.

- [x] Report miktarı yazmamalıdır.

- [x] Kullanıcı tarafından report edilmeyen yorumun report bayrağının içi boş olmalıdır.

**Comment by ummugulsumm** [comment]
## Test Senaryosu

### Yorum kısmında upvote ve report kısmının görünürlüğünün kontrol edilmesi

- **Test Adımları**

1. Ana sayfada Surveys yazısına tıkla.
2. Örnek anketlerden birine tıkla.
3. Sayfayı scroll et.
4. Bir yorum seç.
5. Upvote butonuna bas.
6. Report butonuna bas.


- **Beklenen Sonuç**

1. Anketlerin listelendiği kısma gidilmelidir.
2. Tıklanan anketin bulunduğu sayfaya gidilmelidir.
3. Yorumların olduğu kısma ulaşılmalıdır.
4. Upvote butonunun içi ve report bayrağının içi boş olmalıdır. Daha önceden upvote edildiyse upvote miktarı yazmalıdır. Report miktarı yazmamalıdır. 
5. Upvote butonun içi tasarımda bulunan renk kartelasındaki mavi renk ile boyanmış olmalıdır ve upvote miktarı güncellenmelidir.
6. Report bayrağı kırmızı ile boyanmış olmalıdır.
