### ISSUE TITLE
[Registration]-Kullanıcı Kaydının Sağlanması

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#14]
Kullanıcı, hem sayfa içerisinde bulunan kayıt olma seçeneği ile hem de anket oluşturma ve anket doldurma işlemi bittikten sonra sisteme kayıt olmamışsa kayıt olabilmelidir.

- [x] #38
   
- [ ] #24
        - Kullanıcı Adı  , 
       - E-Mail,
       - Cinsiyet 
       - Ülke,
       - Yaşadığı Şehir,
       - Cinsiyet bilgileri alınarak kayıt edilmelidir.

- [x]  En alt kısımda "Sign Up" butonu bulunmalıdır. Yazı renginin kodu #FFFFFF ve butonun renk kodu #5380EA olmalıdır.

- [x]  Butonun alt kısmında "Have an account? Login" yazmalı ve kullanıcı buraya tıkladığında giriş yapma sayfasına yönlendirilmelidir.

- [ ]  Kullanıcı başarılı bir kayıt olma işlemini sağladığında üst barın sağında bulunan kayıt olma (Sign Up) ve giriş yapma (Login) butonları gitmelidir. Yalnızca kullanıcı ikonu kalmalıdır.

**Comment by ummugulsumm** [comment]
## Test Senaryosu

### Kayıt olma sayfasındaki buton ve Login kısımlarının incelenmesi

- **Test Adımları**

1. Butonun özellikleri ve içeriği kontrol edilmelidir. 
2. Butonun alt kısmındaki yazının içeriği kontrol edilmelidir.                       
3. Butonun altındaki yazıya tıklanmalıdır. 

- **Beklenen Sonuç**

1. En alt kısımda "Sign Up" butonu bulunmalıdır. Yazı renginin kodu #FFFFFF ve butonun renk kodu #5380EA olmalıdır.                                          
2. Butonun alt kısmında "Have an account? Login" yazmalıdır.                                                  
3. Kullanıcı tıkladığında giriş yapma sayfasına yönlendirilmelidir.

### Kayıt olma işlemi başarılı bir şekilde sağlandığında Login ve Sign Up butonunun kontrolü

- **Test Adımları**

1. Kayıt olunmalıdır.                  
2. Üst bar kontrol edilmelidir.

- **Beklenen Sonuç**

1. Başarılı bir şekilde kayıt olunmalıdır.      
2. Login ve Sign Up butonu kaybolmuş olmalıdır. Bunun yerine barda yalnızca ikon kalmalıdır ve ikonun solunda kullanıcı adı yazmalıdır.
