### ISSUE TITLE
[UserProfile]-Kullanıcının Kendi Profili

### ISSUE THREAD

**Issue by SimgeTerzioglu** [bimser-intern/surveysaurus-pm#159]
Bu sayfa kullanıcının kendi profil sayfasıdır.

- [ ] Kullanıcı profil ikonuna bastığında açılan pencerede yer alan "Profile" butonuna tıklarsa yönlendirileceği sayfa kullanıcının porfili, yani bu sayfa olmalıdır.
- [ ] Bu sayfada kullanıcının seçmiş olduğu profil ikonu ve background yer almalıdır.
- [ ] Ayrıca burada sahip olduğu puan, takipçi-takip sayısı, sahip olduğu kupa sayısı ve kupaları görüntülenmelidir. Bu yazıların yanındaki sayılar da tıklanılabilir olmalıdır.
- [ ] Kullanıcı profilindeki survey yazısına tıkladığında "My Surveys" ekranına yönlendirilmelidir. Kullanıcı bu yazıya tıklamasa bile üstüne gelindiğinde belirginleşmesi gerekmektedir.
- [ ] Kullanıcı profilindeki followers ve following yazısına tıkladığında açılan pencerede takipçilerini ve takip edilenleri görüntüleyebilmelidir. Kullanıcı tıklamasa bile follower-following yazılarına üstüne geldiğinde yazıların belirginleşmesi gerekmektedir. #160 
- [ ] Profile sayfasında ayrıca trophies kısmı bulunmaktadır. Totalda şu anlık 5 tane kupa yer almaktadır. #161 
- [ ] Kazanılmayan kupalar buğulu bir şekilde profilde gözükecektir ama etkileşime açık olmamalıdır. Kullanıcı kazanamadığı kupaları yalnızca kendisi görüntüleyebilmelidir. Başka bir user onun profilini görüntülerse kazanılmayan kupalar gösterilmemelidir. Yalnızca kazanılan kupalar gösterilmelidir.
- [ ] Profilindeki arkaplan boyutu 1164x270 olacak şekilde yer almalıdır.
- [ ] Profil ikonu boyutu ise 126x130 olmalıdır.

**Comment by esrayelmen** [comment]
## Test Senaryosu

### "UserProfile" sayfasına erişim 

- **Test Adımları**

1. Kullanıcı girişi yap.
2. Profil ikonuna tıkla.
3. Profile alanına tıkla.

- **Beklenen Sonuç**

1. User Profile sayfasına yönlendirilmelidir.

### "UserProfile" sayfasının düzeni

- **Test Adımları**

1. Kullanıcı girişi yap.
2. Profil ikonuna tıkla.
3. Profile alanına tıkla.
4. Sayfa düzenini incele.

- **Beklenen Sonuç**

1. Sayfanın üst kısmında profil ikonu ve background alanı bulunmalıdır.
2. Background alanının alt kısmında kupalar bölümü bulunmalıdır. Kullanıcı kazanamadığı kupaları buğulu bir şekilde görmelidir. Başka kullanıcılar o profili görüntülediğinde sadece kazanılan kupaları görebilmelidir.

### "UserProfile" sayfasından "My Surveys" alanına yönlendirme yapılabilmesi

- **Test Adımları**

1. Kullanıcı girişi yap.
2. Profil ikonuna tıkla.
3. Profile alanına tıkla.
4. Survey yazısına tıkla.

- **Beklenen Sonuç**

1. Kupalar bölümünün alt kısmında bulunan "My Surveys" alanına yönlendirilmeli.
2. Survey yazısının üzerine imleç geldiğinde yazı belirginleşmelidir.
