### ISSUE TITLE
[UserProfile]-Kullanıcının Kendi Profilinde Profil ve Background Güncellemesi

### ISSUE THREAD

**Issue by SimgeTerzioglu** [bimser-intern/surveysaurus-pm#165]
- [ ] Kullanıcı bu sayfa üzerinden kendine ikon seçebilmelidir.
- [ ] Kullanıcı background üzerindeki sağ altta yer alan aşağı bakan ok tuşuna bastığında küçük bir pencere açılmalıdır. Bu pencere İki seçenek içermelidir. Bunlar "Profile Icon" ve "Profile Background" olmalıdır.
- [ ] Seçili olarak "Profile Icon" kısmı gelmelidir. Kullanıcı dilerse "Profile Background" kısmına geçebilmelidir.
- [ ] Kullanıcı hangi sekmede ise ordaki yazı bold olmalıdır ve altında pembe (E49192) bir çizgi yer alması gerekmektedir.
- [ ] Açılan bu pencereyi kapatabilmek için iki seçenek yer almaktadır. Bunlar: ok tuşuna tekrar basmak veya ekrandaki boş bir alana tıklamak şeklindedir.
- [ ] Kullanıcı kayıt olurken profile icon ve profile backgorund random olarak gelmelidir.
- [ ] Kullanıcı arkaplanı güncellediğinde aşağı bakan ok'ların renkleri değişmektedir. Tasarımda var olan beyaz-siyah arkaplanı için F27E97 renkli yazı ve F27E97 renkli aşağı bakan ok olması gerekmektedir. Diğer arkaplanlar için beyaz olması yeterlidir.
- [ ] Açılan pencerede yer alan profil ikonların boyutları (gösterim için) 40x40 olması gerekmektedir.
- [ ] Açılan profile background penceresinde yer alan arkaplanların boyutu (gösterim için) 123x68 olması gerekmektedir.

**Comment by esrayelmen** [comment]
## Test Senaryosu

### "UserProfile" sayfasından profil ikonunun değiştirilebilmesi

- **Test Adımları**

1. Kullanıcı girişi yap.
2. Kullanıcı ikonuna tıkla.
3. Profile alanına tıkla.
4. Kullanıcı ikonunun sol alt kısmındaki ikona tıkla.
5. Herhangi bir ikona tıkla.

- **Beklenen Sonuç**

1. Profil ikonunun seçilen ikonla değişmesi beklenmektedir.
2. Açılan pencere tekrar ikona tıklanarak veya boş bir alana tıklanarak kapanmalıdır.

### "UserProfile" sayfasından profil arkaplanının değiştirilebilmesi

- **Test Adımları**

1. Kullanıcı girişi yap.
2. Kullanıcı ikonuna tıkla.
3. Profile alanına tıkla.
4. Profil arkaplanının sağ alt kısmındaki ikona tıkla.
5. Herhangi bir arkaplana tıkla.

- **Beklenen Sonuç**

1. Profil arkaplanının seçilen arkaplanla değişmesi beklenmektedir.
2. Açılan pencere tekrar ikona tıklanarak veya boş bir alana tıklanarak kapanmalıdır.
