### ISSUE TITLE
[HomePage]-Sayfada 'Login' ve 'Sign Up' butonları  bulunmalıdır.

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#18]
- [x] "Sign Up" butonuna tıklandığında kayıt olma (Registration) sayfasına yönlendirmelidir. 

- [x]  "Login" butonuna tıklandığında giriş yapma (Login) sayfasına yönlendirmelidir.

- [ ]  Kullanıcı giriş yaptığında veya kayıt olduğunda bu butonlar artık barda olmamalıdır. Bunun yerine barda yalnızca ikon kalmalıdır ve ikonun solunda kullanıcı adı yazmalıdır.

**Comment by ummugulsumm** [comment]
## Test Senaryosu

### Login ve Sign Up butonlarının işlevsellik kontrolü

- **Test Adımları**

1. Login butonuna basılmalıdır.                     
2. Sign Up butonuna basılmalıdır.

- **Beklenen Sonuç**

1. Giriş yapma (Login) sayfasına yönlendirmelidir.                                                     
2. Kayıt olma (Registration) sayfasına yönlendirmelidir.     

### Kullanıcı girişi sağlandığında Login ve Sign Up butonunun kontrolü

- **Test Adımları**

1. Kullanıcı girişi yapılmalıdır.                
2. Üst bar kontrol edilmelidir. 

- **Beklenen Sonuç**

1. Başarılı bir şekilde giriş yapılmalıdır.        
2. Login ve Sign Up butonu kaybolmuş olmalıdır. Bunun yerine barda yalnızca ikon kalmalıdır ve ikonun solunda kullanıcı adı yazmalıdır.

### Kayıt olma işlemi başarılı bir şekilde sağlandığında Login ve Sign Up butonunun kontrolü

- **Test Adımları**

1. Kayıt olunmalıdır.                  
2. Üst bar kontrol edilmelidir.

- **Beklenen Sonuç**

1. Başarılı bir şekilde kayıt olunmalıdır.      
2. Login ve Sign Up butonu kaybolmuş olmalıdır. Bunun yerine barda yalnızca ikon kalmalıdır ve ikonun solunda kullanıcı adı yazmalıdır.
