### ISSUE TITLE
[HomePage]-'Login' ve 'Sign Up' butonlarının en sağında kullanıcı ikonu bulunsun.

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#19]
Kullanıcı kaydolup giriş yapmış ise hesap bilgilerine ve oluşturduğu anketlerine ulaşabilmesi için başlangıç sayfasının en sağında bulunması gereken ikon.

- [x]  İkona tıklandığında açılır menü olmalıdır. Açılır menüde "User Info", "My Surveys" ve "Log out" alanları olmalıdır.

- [ ]  Kullanıcı "User Info" kısmına tıkladığında kendi bilgilerini görüntüleyebildiği sayfaya yönlendirilmelidir.

- [x]  Kullanıcı "My Surveys" kısmına tıkladığında oluşturmuş olduğu anketleri görüntüleyebildiği sayfaya yönlendirilmelidir.

- [x]  Kullanıcı "Log out" kısmına tıkladığında oturumunu kapatabilmelidir. Bu işlemden sonra kullanıcı ana sayfadaki ilk duruma dönmelidir. Üst bardaki "Sign in" ve "Login" butonları geri gelmelidir. 

- [x]  İmleç açılır menüde hangi alana gelirse o alanın rengi koyulaşmalıdır.

- [x] Kullanıcı giriş yapmadan açılır menüdeki seçeneklerden birine tıklarsa giriş yapma (Login) sayfasına yönlendirilmelidir.

**Comment by esrayelmen** [comment]
## Test Senaryosu

### Homepage'de kullanıcı ikonunun işlevsellik kontrolü

- **Test Adımları**

1. Login işlemini gerçekleştir.
2. Kullanıcı ikonuna tıkla.
3. Açılır menüde  "User Info", "My Surveys" ve "Log out" alanlarının varlığını kontrol et.

- **Beklenen Sonuç**

1. İkona tıklandığında açılır menünün gelmesi ve  menüde "User Info", "My Surveys" ve "Log out" alanlarının olması.

### "User Info" alanının işlevsellik kontrolü

- **Test Adımları**

1.Login işlemini gerçekleştir.
2. Kullanıcı ikonuna tıkla.
3. Açılır menüde "User Info" alanına tıkla.

- **Beklenen Sonuç**

1. Kullanıcının kendi bilgilerini görüntüleyebildiği sayfanın açılması.

### "My Surveys" alanının işlevsellik kontrolü

- **Test Adımları**

1. Login işlemini gerçekleştir.
2. Kullanıcı ikonuna tıkla.
3. Açılır menüde "My Surveys" alanına tıkla.

- **Beklenen Sonuç**

1. Kullanıcının oluşturduğu anketleri görüntüleyebildiği sayfanın açılması.

### "Log out" alanının işlevsellik kontrolü

- **Test Adımları**

1. Login işlemini gerçekleştir.
2. Kullanıcı ikonuna tıkla.
3. Açılır menüde "Log out" alanına tıkla.

- **Beklenen Sonuç**

1. Kullanıcının oturumunu kapatabilmesi.
2. Kullanıcı, ana sayfadaki ilk duruma dönmeli.  
3. Üst bardaki "Sign in" ve "Login" butonları geri gelmeli.

### İmlecin açılır menüdeki işlevsellik kontrolü

- **Test Adımları**

1.Kullanıcı ikonuna tıkla.
2.İmleci açılır menüdeki içeriklerin üzerinde gezdir.

- **Beklenen Sonuç**

1. İmlecin üzerinde bulunduğu alanın renginin koyulaşması.

### Kullanıcı giriş yapmadan açılır menüdeki seçeneklerden birine tıklarsa login sayfasına yönlendirmesi

- **Test Adımları**

1. Hesaba giriş yapılmamış durumda ol.
2. Kullanıcı ikonuna tıkla.
3. Açılır menüdeki seçeneklerden her birine tıkla. 

- **Beklenen Sonuç**

1. Kullanıcının Login sayfasına yönlendirilmesi.
