### ISSUE TITLE
[Homepage]-Sayfanın alt kısmında anketlerin listelendiği bir bölüm yer alacak.

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#20]
- [x]  Başlangıç sayfasının scroll edilmesiyle sayfanın en altında anketler listelenmelidir. Kullanıcı, başlangıç sayfasında barda bulunan "Surveys" butonuna tıklayarak da anket listesine ulaşılabilmelidir

- [x] "Our Sample Surveys" yazısının alt kısmında örnek anketler yer almalıdır. 

- [x] Kullanıcı tıkladığı ankete yönlendirilmelidir. İmleç hangi anketin üzerinde geziniyorsa o anket belirginleşmelidir.

- [x] Örnek anketlerin alt kısmında, ortada "Create A Survey" yazmalıdır. Bu yazının renk kodu #000000 şeklinde olmalıdır.

- [x]  Bu yazının altında "Click to create" butonu olmalıdır. Bu yazının renk kodu #D3D8FF, buton rengi ise #5380EA şeklinde olmalıdır. 

- [x]  İmleç "Click to create" butonunun üzerine geldiğinde buton bir miktar büyümelidir. Bu butona tıklandığında anket oluşturma sayfasına yönlendirmelidir.

**Comment by ummugulsumm** [comment]
## Test Senaryosu

### Anketlerin listelendiği bölüme ulaşılması

- **Test Adımları**

1. Sayfa scroll edilip en alta inilmelidir.               
2. Giriş kısmındayken üst bardan "Surveys" butonuna tıklanmalıdır.

- **Beklenen Sonuç**

1 - 2. Anket listesine ulaşılabilmelidir. "Our Sample Surveys" yazısının alt kısmında örnek anketler yer almalıdır.   

### Anket listelenme kısmının özelliklerinin kontrolü

- **Test Adımları**

1. İmleç anketlerin üzerinde sırayla gezdirilmelidir.             
2. Anketlere sırayla tıklanmalıdır.

- **Beklenen Sonuç**

1. İmlecin üzerinde olduğu anket belirginleşmelir.                                              
2. Tıklanılan anketin olduğu sayfaya yönlendirme sağlanmalıdır.

### Anket listesinin alt kısmının incelenmesi

- **Test Adımları**

1. Anket listesinin altında yer alan yazı ve rengi incelenmelidir.     
2. Onun altında bulunan buton, butonun içeriği ve rengi kontrol edilmelidir.                     
3. İmleç butonun üzerine getirilmelidir.   
4. Butona tıklanmalıdır.

- **Beklenen Sonuç**

1. Ortada "Create A Survey" yazmalıdır. Bu yazının renk kodu #000000 şeklinde olmalıdır.                                                              
2. "Click to create" butonu olmalıdır. Bu yazının renk kodu #D3D8FF, buton rengi ise #5380EA şeklinde olmalıdır.                          
3. İmleç butonun üzerine geldiğinde buton bir miktar büyümelidir.                                     
4. Butona tıklandığında anket oluşturma sayfasına yönlendirmelidir.
