### ISSUE TITLE
[HomePage-]Sayfanın en üstünde bulununan barın en solunda 'Home', 'About', 'Surveys' butonları bulunmalıdır.

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#21]
Üst Barın Solunda Bulunan Butonlar
----------------------------------------------

      Üst barın en sol kısmında "Home", onun sağında "About" ve onun sağında da "Surveys" yazısı yer almalıdır.
 İmleç, yazıların üzerine geldiğinde yazılar belirginleşmelidir. Yani bir miktar büyümelidir.

- [x]  Üst bardaki "Home" yazısına tıklandığında ana sayfanın en başına yönlendirmelidir. 

- [x] Üst bardaki "About" yazısına tıklandığında ana sayfadaki about kısmına inilmelidir.

- [x]  Üst bardaki "Surveys" kısmına tıklandığında ana sayfadaki  uygulamada var olan anket listesinin bulunduğu alana inilmelidir.

Ana Sayfanın Ortasında Bulunan About Alanı
---------------------------------------------------
- [x]  Bu yazıların alt kısmındaki sayfa "About Us" kısmını içermelidir. Bu yazı ortada yer almalı ve #000000 renk kodunda olmalıdır.

- [x]  "About Us" yazısının altında #FFFFFF renk kodunda bir alan olmalıdır. Bu alana hakkımızda yazısı eklenecektir. Alanın renk opaklığı %40 olmalıdır.

- [x] "About Us" alanının altında "Our Sample Surveys" yazısı olmalıdır. Yazının renk kodu #000000 şeklinde olmalıdır.

**Comment by esrayelmen** [comment]
## Test Senaryosu

### Üst bar üzerinde imlecin işlevsellik kontrolü

- **Test Adımları**

1. İmleci "Home" butonunun üzerine getir. 
2. İmleci "About" butonunun üzerine getir. 
3. İmleci "Surveys" butonunun üzerine getir.

- **Beklenen Sonuç**

1. Yazıların belirginleşmesi ve bir miktar büyümesi.

### Ana sayfanın en başına yönlendirme yapılması

- **Test Adımları**

1. Üst bardaki "Home" butonuna tıkla.

- **Beklenen Sonuç**

1. Homepage sayfasının en başına dönmeli.

### About alanına yönlendirme yapılması.

- **Test Adımları**

1. Üst bardaki "About" butonuna tıkla

- **Beklenen Sonuç**

1. Ana sayfada bulunan about alanına inilmesi.

### Surveys alanına yönlendirme yapılması

- **Test Adımları**

1. Üst bardaki "Surveys" butonuna tıkla.

- **Beklenen Sonuç**

1.  Ana sayfadaki uygulamada var olan anket listesinin bulunduğu alana inilmesi.

### Anasayfanın orta kısmında "About Us" alanı bulunması

- **Test Adımları**

1. Sayfayı scroll et.
2. "About Us" yazısının bulunduğu alanı, konumunu ve renk kodunu incele. 

- **Beklenen Sonuç**

1. "About Us" yazısının orta kısımda yer alması ve #000000 renk kodunda olması.
2. "About Us" yazısının altında #FFFFFF renk kodunda bir alan olmalı ve renk opaklığı %40 olmalı.
3. "About Us" alanının altında #000000 renk koduna sahip "Our Sample Surveys" yazısı bulunmalı.
