### ISSUE TITLE
[Registration]-Kayıt olma işlemi yapılırken kullanıcıdan- Kullanıcı Adı  , E-Mail, Cinsiyet- Ülke, Yaşadığı Şehir ve Parola bilgileri alınarak kayıt edilmelidir.

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#24]
- [x]  İstenilen bilgiler zorunlu olduğu için yanlarında kırmızı yıldız işareti bulunmalıdır.

- [x]  İlk olarak "Name" bilgisi istenir. Kullanıcının adını yazabileceği alanda "Enter your name" yazmalıdır. Kullanıcı adını yazmaya başladığında bu yazı gider.

- [x] İkinci olarak istenilen bilgi "E-mail Address" bilgisidir. Bu alanda "Enter your e-mail address" yazmalıdır. Kullanıcı bu alanı kullanmaya başladığında yazı gider.

- [x]  Üçüncü olarak istenilen bilgi "Choose Gender" bilgisidir. Bu alanda seçim yapılır. Yer alan seçenekler "Kadın, "Erkek" ve "Belirtmek istemiyorum" şeklinde olmalıdır.

- [x]  Dördüncü olarak istenilen bilgi "Select Country" bilgisidir. Kullanıcı ülke seçimi yaparken ülkeler listelenmelidir ve kullanıcı bunlardan birini seçebilmelidir.

- [x]  Kullanıcı bu alana yazı da yazabilmelidir ve eğer yalnızca "A" harfi yazılmışsa bu harf ile başlayan ülkeler getirilmelidir. Büyük harf küçük harf duyarlılığı olmamalıdır.

- [x]  Beşinci olarak istenilen bilgi "Select City" bilgisidir. Şehir seçimi yapılırken seçilen ülkeye göre şehirler listelenmelidir.

- [x]  Son olarak istenilen bilgi "Password" bilgisidir. Bu alanda "Enter your password" yazmalıdır. Kullanıcı bu alanı kullanmaya başladığında yazı gider.Şifre ilk olarak gizli olarak yazılır. Kullanıcı şifreyi istediğinde görünür kılabilir ve tekrardan gizleyebilir.
 Kullanıcı en az sekiz karakterli bir şifre girmelidir. Şifre yalnızca harfler, sayılar ve noktalama işaretleri ile sağlanmalıdır. Kullanıcı sekiz karakterden az sayıda bir şifre girdiğinde veya istenilenin dışında bir karakter kullandığında bunun hakkında uyarılmalıdır.

- [x]  Kullanıcıdan bu bilgilerin alınması zorunludur. Eğer bilgilerden biri eksik ise kayıt işlemi tamamlanmaz ve kullanıcı eksik alan için uyarılır.

**Comment by ummugulsumm** [comment]
## Test Senaryosu

### Kayıt olma sayfasının özelliklerinin incelenmesi

- **Test Adımları**

1. İstenilen bilgilerin sırası ve isimleri kontrol edilmelidir.  

- **Beklenen Sonuç**

1. İlk olarak "Name" bilgisi, ikinci olarak "E-mail Address"  bilgisi, üçüncü olarak "Choose Gender" bilgisi, dördüncü olarak "Select Country" bilgisi, beşince olarak "Select City" bilgisi ve son olarak da "Password" bilgisi istenmelidir. İstenilen bilgiler zorunlu olduğundan yanlarında kırmızı yıldız işareti olmalıdır.   

### Name, E-mail Address ve Pasword kısımlarının özelliklerinin incelenmesi

- **Test Adımları**

1. Kullanıcıdan yazılı bilgi alma kutularının özellikleri incelenmelidir.               
2. Bilgi alma kutularına yazı girişi yapılmalıdır.

- **Beklenen Sonuç**

1. Kullanıcının adını yazabileceği alanda "Enter your name", mail adresini yazabileceği alanda "Enter your e-mail address", parola yazabileceği alanda "Enter your password" yazmalıdır.                                                                        
2. Yazı girişi olduğu zaman alanlarda var olan yazılar kaybolmalıdır.

### Choose Gender kısmının özelliklerinin incelenmesi

- **Test Adımları**

1. Üzerine tıklanmalıdır.               
2. Seçeneklerden birine tıklanmalıdır.

- **Beklenen Sonuç**

1. Üzerine tıklandığında 3 tane seçenek açılmalıdır. Yer alan seçenekler "Kadın, "Erkek" ve "Belirtmek istemiyorum" şeklinde olmalıdır. Kullanıcı içlerinden bir tanesini seçebilmelidir.                                
2. Tıklanılan seçenek kullanıcının seçimi olarak seçilmiş olmalıdır. 

### Select Country kısmının özelliklerinin incelenmesi

- **Test Adımları**

1. Üzerine tıklanmalıdır.               
2. Alana büyük harf girişi yapılmalıdır.      
3. Alana aynı harfle küçük harf girişi yapılmalıdır.              
4. Seçeneklerden birine tıklanmalıdır.

- **Beklenen Sonuç**

1. Üzerine tıklandığında ülkeler listelenmelidir. Kullanıcı içlerinden birini seçebilmelidir.                                                
2. Harf girişini kabul etmelidir ve ilgili harfle başlayan ülkeler getirilmelidir.                                                  
3. Sonuç ikinci adımla aynı olmalıdır.         
4. Tıklanılan seçenek kullanıcının seçimi olarak seçilmiş olmalıdır.  

### Select City kısmının özelliklerinin incelenmesi

- **Test Adımları**

1. Üzerine tıklanmalıdır.             
2. Alana büyük harf girişi yapılmalıdır.            
3. Alana aynı harfle küçük harf girişi yapılmalıdır.                     
4. Seçeneklerden birine tıklanmalıdır.

- **Beklenen Sonuç**

1. Seçilen ülkeye göre şehirler listelenmiş olmalıdır. Kullanıcı içlerinden birini seçebilmelidir.                                                   
2. Harf girişini kabul etmelidir ve ilgili harfle başlayan şehirler getirilmelidir.                                             
3. Sonuç ikinci adımla aynı olmalıdır.                
4. Tıklanılan seçenek kullanıcının seçimi olarak seçilmiş olmalıdır.
