### ISSUE TITLE
[AndroidCreateSurvey]-Sayfada, kullanıcının anketine ait soruyu yazabileceği ve sorunun seçeneklerini oluşturabileceği alan bulunmalıdır.

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#26]
Kullanıcı ilk etapta tek soruluk anketler oluşturabilecektir
 
- [x] Sayfada kullanıcının sorusunu yazabileceği bir text alanı olmalıdır. Alanın içinde silik bir şekilde 'Add your question' yazmalıdır.

- [x] Soru alanının alt kısmında ankete isim verilebilen bir alan olmalıdır. Bu alanın içinde silik bir şekilde "Survey name" yazmalıdır.

- [x] Anket ismi alanının altında kullanıcının sorusuna ait seçeneklerini yazabileceği alanı olmalıdır.(Test sorusunun şıkları gibi düşünülebilir).

- [x] #51

- [x]  Kullanıcının anketini kaydedebilmesi için sayfanın sağ alt kısmında 'Create' butonu bulunmalıdır. Buton ile anket oluşturma işlemini tamamlayabilmelidir.

- [x]  Anket oluşturma işlemi bittikten sonra kullanıcı giriş yapmamış ise 'Sign In' sayfasına yönlendirilmelidir.

**Comment by esrayelmen** [comment]
## Test Senaryosu

### Create Survey sayfasının düzeni

- **Test Adımları**

1. Sayfa düzenini incele.

- **Beklenen Sonuç**

1. Kullanıcının soru yazabileceği text alanı bulunması ve alanın içinde silik bir şekilde "Add your question" yazmalı.
2. Soru alanının altında soruya ait seçeneklerin yazılabileceği alan olmalı ve alanın içinde silik bir şekilde "Add your option" yazmalı. 
3. Seçenek alanının altında "Add option" butonu olmalı.
4. Sayfanın sağ alt kısmında "Create" butonu olmalı.

### "Add option" butonunun işlevsellik kontrolü

- **Test Adımları**

1. "Add option" butonuna bas.

- **Beklenen Sonuç**

Yeni seçenek oluşturma alanının oluşması.

### Giriş yapmış kullanıcı için "Create" butonunun işlevsellik kontrolü

- **Test Adımları**

1. Kullanıcı girişi yap.
2. Question alanını doldur.
3. Seçenek alanını doldur.
4. "Create" butonuna bas.

- **Beklenen Sonuç**

1. Anket oluşturma işleminin tamamlanması. 

### Giriş yapmamış kullanıcı için "Create" butonunun işlevsellik kontrolü

- **Test Adımları**

1. Kullanıcı girişi yapmamış durumda ol.
2. Question alanını doldur.
3. Seçenek alanını doldur.
4. "Create" butonuna bas.

- **Beklenen Sonuç**

1. Kullanıcı "Sign In" sayfasına yönlendirilmeli.
