### ISSUE TITLE
[AndroidCreateSurvey]-Android Anket Oluşturma Sayfasının Düzeni

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#27]
Kullanıcı bu sayfada bulunan açılır menü ile ana sayfaya dönme (Home), giriş yapma(Login) ve uygulamaya kaydolma (Sign Up) seçeneklerine ulaşabilmeli ve sayfada bulunan ikon yardımıyla hesap bilgilerine ulaşabilmelidir.

- [x]  Sayfanın sol üst kısmında üç çizik halinde ikon bulunmalı ve bu ikona basılabilmelidir. İkona basıldığında 'Home',
 'Sign Up','Login' işlemleri çıkmalıdır. Kullanıcı giriş yapmış ise 'Sign In','Sign up' işlemleri yerine '@username'
yazmalıdır.
  
- [x]  Sayfanın üstünde orta kısımda uygulamanın logosu bulunmalıdır.  

- [x]  Sayfanın sağ üst köşesinde kullanıcının profil bilgilerine ulaşabileceği profil ikonu bulunmalıdır.Bu ikona tıklandığında giriş yapılmış ise kullanıcı kendine ait bilgileri(User Profile) ve oluşturduğu anketlerin listesine (My Surveys) ulaşabilmelidir.

- [x]  Sayfada kullanıcının sorusunu yazabileceği bir text alanı olmalıdır. Alanın içinde silik bir şekilde 'Add your question' yazmalıdır.
 Soru alanının alt kısmında ankete isim verilebilen bir alan olmalıdır. Bu alanın içinde silik bir şekilde "Survey name" yazmalıdır.
 Anket ismi alanının altında kullanıcının sorusuna ait seçeneklerini yazabileceği alanı olmalıdır.(Test sorusunun şıkları gibi düşünülebilir).

**Comment by ummugulsumm** [comment]
## Test Senaryosu

### Sayfanın üst kısmının incelenmesi

- **Test Adımları**
 
1. Üst barın içeriği ve konumlanışı kontrol edilmelidir.

- **Beklenen Sonuç**

1. Sayfanın üst barında orta kısımda uygulamanın logosu bulunmalıdır. Sayfanın sağ üst köşesinde profil ikonu bulunmalıdır. Sayfanın sol üst kısmında üç çizik halinde ikon bulunmalı.

### Profil ikonunun incelenmesi

- **Test Adımları**

1. Profil ikonuna tıkla.
2. Başarılı bir şekilde giriş yap. 
3. Üst bardan profil ikonuna tıkla.

- **Beklenen Sonuç**

1. İkon tıklanılabilir olmalıdır.
2. Giriş yapılmalıdır.
3. Menü açılmalıdır. "User Info", "My surveys" ve "Log out" seçeneklerine ulaşılabilmelidir. 

### Üç çizgi ikonunun incelenmesi

- **Test Adımları**

1. Giriş yapmadan üç çizgi ikonuna tıkla. 
2. Başarılı bir şekilde giriş yap. 
3. Giriş yaptıktan sonra üç çizgi ikonuna tıkla.

- **Beklenen Sonuç**

1. 'Home' 'Sign Up','Login' işlemleri çıkmalıdır.
2. Giriş yapılmalıdır. 
3. Sign up ve Login kısımları kaybolmuş olmalıdır. Sign Up kısmı yerinde '@username'
yazmalıdır.

**Not:** Son task için test senaryosu #26 numaralı issue içindedir.
