### ISSUE TITLE
[AndroidLogin]-Kullanıcı login sayfası aracılığıyla hesabına giriş yapabilmelidir.

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#30]
- [ ] #42
   
- [x] Kullanıcının giriş yapabilmesi için 'E-Mail' bilgisinin alınacağı bir text alanı olmalıdır. Text alanının üstünde E-Mail yazısı bulunmalıdır.

- [x] E-Mail bilgisini girdiği text alanının altında parolasını girebileceği parola alanı bulunmalıdır.

- [x] Parola alanının altında 'Login' butonu bulunmalıdır.

- [x] Bilgilerini girdikten sonra 'Login' butonuna basarak uygulamaya giriş yapabilmelidir.

**Comment by esrayelmen** [comment]
## Test Senaryosu

### Login sayfasında kullanıcı giriş alanının düzeni 

- **Test Adımları**

1. E-mail alanını kontrol et.
2. Parola alanını kontrol et.
3. Login butonunu kontrol et.

- **Beklenen Sonuç**

1. E-mail girişi yapılabilecek text alanın bulunması ve bu alanın üstünde "Email address" yazısının bulunması.
2. E-mail text alanının altında parola girilecek alanın bulunması ve bu alanın üstünde "Password" yazısının bulunması.
3. Parola alanının altında "Login" butonunun bulunması.

### Kullanıcının geçerli e-mail ve parola girmesi

- **Test Adımları**

1. Geçerli E-mail adresi gir.
2. Geçerli parola gir.
3. Login butonuna bas.

- **Beklenen Sonuç**

1. Kullanıcının uygulamaya giriş yapabilmesi.

### Kullanıcının geçersiz e-mail adresi girmesi

- **Test Adımları**

1. Geçersiz E-mail adresi gir.
2. Geçerli parola gir.
3. Login butonuna bas.

- **Beklenen Sonuç**

1. Kullanıcının uygulamaya giriş yapamaması.

### Kullanıcının geçersiz parola girmesi

- **Test Adımları**

1. Geçerli E-mail adresi gir.
2. Geçersiz parola gir.
3. Login butonuna bas.

- **Beklenen Sonuç**

1. Kullanıcının uygulamaya giriş yapamaması.

### Kullanıcının geçersiz e-mail ve parola girmesi

- **Test Adımları**

1. Geçersiz E-mail adresi gir.
2. Geçersiz parola gir.
3. Login butonuna bas.

- **Beklenen Sonuç**

1. Kullanıcının uygulamaya giriş yapamaması.

### E-mail alanının boş bırakılması

- **Test Adımları**

1. E-mail alanını boş bırak.
2. Parola alanını doldur.
3. Login butonuna tıkla

- **Beklenen Sonuç**

1. Kullanıcının uygulamaya giriş yapamaması.

### Parola alanının boş bırakılması

- **Test Adımları**

1. E-mail alanını doldur.
2. Parola alanını boş bırak.
3. Login butonuna tıkla. 

- **Beklenen Sonuç**

1. Kullanıcının uygulamaya giriş yapamaması.
