### ISSUE TITLE
[AndroidLogin]-Android Uygulamada Kullanıcı Giriş Sayfasının Düzeni

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#31]
- [x] Sayfanın sol üst kısmında üç çizik halinde ikon bulunmalı ve bu ikona basılabilmelidir. İkona basıldığında 'Home', 'Sign In','Sign Up' işlemleri çıkmalıdır.Kullanıcı giriş yapmış ise 'Sign In','Sign Up' işlemleri yerine '@username'
yazmalıdır.
   
- [x] Sayfanın üstünde orta kısımda uygulamanın logosu bulunmalıdır. 

- [x] Sayfanın sağ üst köşesinde kullanıcının profil bilgilerine ulaşabileceği profil ikonu bulunmalıdır.Bu ikona tıklandığında giriş yapılmış ise kullanıcı kendine ait bilgileri ve oluşturduğu anketlerin listesine ulaşabilmelidir.

- [x] Sayfanın orta sağ kısmında ise bilgilerini girebileceği alanlar olmalıdır.

**Comment by esrayelmen** [comment]
## Test Senaryosu

### Login sayfasının düzeni

- **Test Adımları**

1. Sayfanın sol üst kısmını kontrol et.
2. Sayfanın üst orta kısmını kontrol et.
3. Sayfanın orta sağ kısmını kontrol et.
4. Sayfanın sağ üst kısmını kontrol et.

- **Beklenen Sonuç**

1. Sayfanın sol üstünde üç çizik şeklinde "User Options" ikonu bulunmalı.
2. Sayfanın üst orta kısmında uygulama logosu bulunmalı.
3. Sayfanın orta sağ kısmında email ve şifre bilgilerinin girilebileceği alanlar olmalı.
4. Sayfanın sağ üst kısmında profil ikonu bulunmalı. 

### Login sayfasındaki "User Options" ikonunun içerik kontrolü

- **Test Adımları**

1. "User Options" ikonuna tıkla.
2. İçeriği kontrol et.
3. Geçerli e-mail adresi gir.
4. Geçerli parola gir.
5. Login butonuna tıkla.
6. "User Options" ikonuna tıkla.
7. İçeriği kontrol et.

- **Beklenen Sonuç**

1. Kullanıcı giriş yapmadan önce "Home",  "Sign Up", "Login" işlemleri çıkmalı.
2. Kullanıcı giriş yaptıktan sonra "Sign Up", "Login" işlemleri silinmeli ve yerine @username ve "Logout" yazmalı.

### Login sayfasındaki profil ikonunun içerik kontrolü

- **Test Adımları**

1. Profil ikonuna tıkla.
2. Geçerli e-mail adresi gir.
3. Geçerli parola gir.
4. Login butonuna tıkla.
5. Profil ikonuna tıkla.
6. İçeriği kontrol et.

- **Beklenen Sonuç**

1. Kullanıcı giriş yapmadan önce ikonun yalnızca tıklanabilir olması.
2. Kullanıcı giriş yaptıktan sonra profil ikonundan kendi bilgilerine ve oluşturduğu anket listesine ulaşabilmeli.
