### ISSUE TITLE
[AndroidRegistration]-Kullanıcıdan Kullanıcı Adı , E-Mail, Cinsiyet, Ülke, Yaşadığı Şehir ve Parola bilgileri alınarak kayıt edilmelidir.

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#32]
- [x]  İstenilen bilgiler zorunlu olduğu için yanlarında kırmızı yıldız işareti bulunmalıdır.

- [x]  İlk olarak "Name" bilgisi istenir. Kullanıcının adını yazabileceği alanda "Enter your name" yazmalıdır. Kullanıcı adını yazmaya başladığında bu yazı gider.

- [x] İkinci olarak istenilen bilgi "E-mail Address" bilgisidir. Bu alanda "Enter your e-mail address" yazmalıdır. Kullanıcı bu alanı kullanmaya başladığında yazı gider.

- [x]  Üçüncü olarak istenilen bilgi "Choose Gender" bilgisidir. Bu alanda seçim yapılır. Yer alan seçenekler "Kadın, "Erkek" ve "Belirtmek istemiyorum" şeklinde olmalıdır.

- [x]  Dördüncü olarak istenilen bilgi "Select Country" bilgisidir. Kullanıcı ülke seçimi yaparken ülkeler listelenmelidir ve kullanıcı bunlardan birini seçebilmelidir.

- [x]  Kullanıcı bu alana yazı da yazabilmelidir ve eğer yalnızca "A" harfi yazılmışsa bu harf ile başlayan ülkeler getirilmelidir. Büyük harf küçük harf duyarlılığı olmamalıdır.

- [x]  Beşinci olarak istenilen bilgi "Select City" bilgisidir. Şehir seçimi yapılırken seçilen ülkeye göre şehirler listelenmelidir.

- [x]  Son olarak istenilen bilgi "Password" bilgisidir. Bu alanda "Enter your password" yazmalıdır. Kullanıcı bu alanı kullanmaya başladığında yazı gider.Şifre ilk olarak gizli olarak yazılır. Kullanıcı şifreyi istediğinde görünür kılabilir ve tekrardan gizleyebilir.
 Kullanıcı en az sekiz karakterli bir şifre girmelidir. Şifre yalnızca harfler, sayılar ve noktalama işaretleri ile sağlanmalıdır. Kullanıcı sekiz karakterden az sayıda bir şifre girdiğinde veya istenilenin dışında bir karakter kullandığında bunun hakkında uyarılmalıdır.

- [x]  Kullanıcıdan bu bilgilerin alınması zorunludur. Eğer bilgilerden biri eksik ise kayıt işlemi tamamlanmaz ve kullanıcı eksik alan için uyarılır.

**Comment by SimgeTerzioglu** [comment]
## Test Senaryosu

### Kayıt olma sayfasının özelliklerinin incelenmesi

- **Test Adımları**

1. İstenilen bilgilerin sırası ve isimleri kontrol edilmelidir.  

- **Beklenen Sonuç**

1. İlk olarak "Name" bilgisi, ikinci olarak "E-mail Address"  bilgisi, üçüncü olarak "Choose Gender" bilgisi, dördüncü olarak "Select Country" bilgisi, beşince olarak "Select City" bilgisi ve son olarak da "Password" bilgisi istenmelidir. İstenilen bilgiler zorunlu olduğundan yanlarında kırmızı yıldız işareti olmalıdır.   

### Name, E-mail Address ve Password kısımlarının özelliklerinin incelenmesi

- **Test Adımları**

1. Kullanıcıdan yazılı bilgi alma kutularının özellikleri incelenmelidir.               
2. Bilgi alma kutularına yazı girişi yapılmalıdır.

- **Beklenen Sonuç**

1. Kullanıcının adını yazabileceği alanda "Enter your name", mail adresini yazabileceği alanda "Enter your e-mail address", parola yazabileceği alanda "Enter your password" yazmalıdır.                                                                        
2. Yazı girişi olduğu zaman alanlarda var olan yazılar kaybolmalıdır.

### Choose Gender kısmının özelliklerinin incelenmesi

- **Test Adımları**

1. Üzerine tıklanmalıdır.               
2. Seçeneklerden birine tıklanmalıdır.

- **Beklenen Sonuç**

1. Üzerine tıklandığında 3 tane seçenek açılmalıdır. Yer alan seçenekler "Kadın, "Erkek" ve "Belirtmek istemiyorum" şeklinde olmalıdır. Kullanıcı içlerinden bir tanesini seçebilmelidir.                                
2. Tıklanılan seçenek kullanıcının seçimi olarak seçilmiş olmalıdır. 

### Select Country kısmının özelliklerinin incelenmesi

- **Test Adımları**

1. Üzerine tıklanmalıdır.               
2. Alana büyük harf girişi yapılmalıdır.      
3. Alana aynı harfle küçük harf girişi yapılmalıdır.              
4. Seçeneklerden birine tıklanmalıdır.

- **Beklenen Sonuç**

1. Üzerine tıklandığında ülkeler listelenmelidir. Kullanıcı içlerinden birini seçebilmelidir.                                                
2. Harf girişini kabul etmelidir ve ilgili harfle başlayan ülkeler getirilmelidir.                                                  
3. Sonuç ikinci adımla aynı olmalıdır.         
4. Tıklanılan seçenek kullanıcının seçimi olarak seçilmiş olmalıdır.  

### Select City kısmının özelliklerinin incelenmesi

- **Test Adımları**

1. Üzerine tıklanmalıdır.             
2. Alana büyük harf girişi yapılmalıdır.            
3. Alana aynı harfle küçük harf girişi yapılmalıdır.                     
4. Seçeneklerden birine tıklanmalıdır.

- **Beklenen Sonuç**

1. Seçilen ülkeye göre şehirler listelenmiş olmalıdır. Kullanıcı içlerinden birini seçebilmelidir.                                                   
2. Harf girişini kabul etmelidir ve ilgili harfle başlayan şehirler getirilmelidir.                                             
3. Sonuç ikinci adımla aynı olmalıdır.                
4. Tıklanılan seçenek kullanıcının seçimi olarak seçilmiş olmalıdır. 

### Şifre ikonunun kontrolü

- **Test Adımları** 

1. Surveysaurus uygulamasına girilir.
2. Sign up butonuna tıklanır.
3. Şifre alanı kontrol edilir.

- **Beklenen Sonuç**

1. Şifre alanında ikon bulunmalıdır.

### Şifre ikonunun işlevsellik kontrolü

- **Test Adımları** 

1. Surveysaurus uygulamasına girilir.
2. Sign up butonuna tıklanır.
3. Şifre alanına şifre girilir.
4. Şifre alanındaki ikona tıklanır.
5. İkona yeniden tıklanır.

- **Beklenen Sonuç**

1. İlk etapta girilen şifre görünmez durumda olmalıdır.
2. İkona ilk tıklama gerçekleştiğinde şifre görünür duruma geçmelidir.
3. İkona yeniden tıklanıldığında şifre tekrardan görünmez duruma geçmelidir.

### Kullanıcıdan geçerli veriler alınarak kayıt işlemi yapılmasının kontrolü

- **Test Adımları**

1. Surveysaurus uygulamasına girilir.
4. Sign up butonuna tıklanır.
6. kullanıcı adı bilgisi girilir.
7. E-mail bilgisi girilir.
8. Cinsiyet bilgisi seçilir.
9. Ülke bilgisi için seçim yapılır.
10. Şehir bilgisi için seçim yapılır.
11. Parola girilir.
12. Sign up butonuna tıklanır.

- **Beklenen Sonuç** 

1. Kullanıcı başarılı bir şekilde sisteme kayıt olabilmelidir.

### Kullanıcıdan geçersiz veriler alınarak kayıt işlemi yapılmasının kontrolü

#### *Kullanıcı adı girilmemesi durumu*

- **Test Adımları**

1. Surveysaurus uygulamasına girilir.
2.  Sign up butonuna tıklanır.
5. Kullanıcı adı bilgisi **girilmez**.
6. E-mail bilgisi girilir.
7. Cinsiyet bilgisi seçilir.
8. Ülke bilgisi için seçim yapılır.
9. Şehir bilgisi için seçim yapılır.
10. Parola girilir.
11. Sign up butonuna tıklanır.

- **Beklenen Sonuç**

1. Kullanıcı sisteme kayıt olmamalıdır.
2. Kullanıcı hata mesajı almalıdır.

#### *E-mail girilmemesi durumu*

- **Test Adımları**

1. Surveysaurus uygulamasına girilir.
2. Sign up butonuna tıklanır.
5. Kullanıcı adı bilgisi girilir.
6. E-mail bilgisi **girilmez**.
7. Cinsiyet bilgisi seçilir.
8. Ülke bilgisi için seçim yapılır.
9. Şehir bilgisi için seçim yapılır.
10. Parola girilir.
11. Sign up butonuna tıklanır.

- **Beklenen Sonuç**

1. Kullanıcı sisteme kayıt olmamalıdır.
2. Kullanıcı hata mesajı almalıdır.

#### *Cinsiyet seçilmemesi durumu*

- **Test Adımları**

1. Surveysaurus uygulamasına girilir.
2. Sign up butonuna tıklanır.
4. Kullanıcı adı bilgisi girilir.
5. E-mail bilgisi girilir.
6. Cinsiyet bilgisi **seçilmez**.
7. Ülke bilgisi için seçim yapılır.
8. Şehir bilgisi için seçim yapılır.
9. Parola girilir.
10. Sign up butonuna tıklanır.

- **Beklenen Sonuç**

1. Kullanıcı sisteme kayıt olmamalıdır.
2. Kullanıcı hata mesajı almalıdır.

#### *Ülke seçilmemesi durumu*

- **Test Adımları**

1. Surveysaurus uygulamasına girilir.
2. Sign up butonuna tıklanır.
3. Kullanıcı adı bilgisi girilir.
4. E-mail bilgisi girilir.
6. Cinsiyet bilgisi seçilir.
7. Ülke bilgisi **seçilmez**.
8. Şehir bilgisi için seçim yapılır.
9. Parola girilir.
10. Sign up butonuna tıklanır.

- **Beklenen Sonuç**

1. Kullanıcı sisteme kayıt olmamalıdır.
2. Kullanıcı hata mesajı almalıdır.

#### *Şehir seçilmemesi durumu*

- **Test Adımları**

1. Surveysaurus uygulamasına girilir.
2. Sign up butonuna tıklanır.
3. Kullanıcı adı bilgisi girilir.
4. E-mail bilgisi girilir.
5. Cinsiyet bilgisi seçilir.
6. Ülke bilgisi için seçim yapılır.
7. Şehir bilgisi **seçilmez**.
8. Parola girilir.
9. Sign up butonuna tıklanır.

- **Beklenen Sonuç**

1. Kullanıcı sisteme kayıt olmamalıdır.
2. Kullanıcı hata mesajı almalıdır.

#### *Parola girilmemesi durumu*

- **Test Adımları**

1. Surveysaurus uygulamasına girilir.
2. Sign up butonuna tıklanır.
3. Kullanıcı adı bilgisi girilir.
4. E-mail bilgisi girilir.
5. Cinsiyet bilgisi seçilir.
6. Ülke bilgisi için seçim yapılır.
7. Şehir bilgisi için seçim yapılır.
8. Parola **girilmez**.
9. Sign up butonuna tıklanır.

- **Beklenen Sonuç**

1. Kullanıcı sisteme kayıt olmamalıdır.
2. Kullanıcı hata mesajı almalıdır.

### Kullanıcıdan geçerli şifre alınması kontrolü

- **Test Adımları**

1. Surveysaurus uygulamasına girilir.
2. Sign up butonuna tıklanır.
3. Şifre alanına geçerli bir şifre girilir.
4. Sign up butonuna tıklanır.

- **Beklenen Sonuç**

1. Kullanıcı şifre alanı için hata almamalıdır.

### Kullanıcıdan geçersiz şifre alınması kontrolü

#### *Sekiz karakterden az karakter girilmesi durumu*

- **Test Adımları**

1. Surveysaurus uygulamasına girilir.
2. Sign up butonuna tıklanır.
3. Şifre alanına sekiz karakterden az karakter içeren bir şifre girilir.
4. Sign up butonuna tıklanır.

- **Beklenen Sonuç**

1. Kullanıcı şifre alanı için hata almalıdır.

#### *Harf, sayı ve noktalama işaretleri dışında karakter girilmesi durumu*

- **Test Adımları**

1. Surveysaurus uygulamasına girilir.
2. Sign up butonuna tıklanır.
3. Harf, sayı ve noktalama işareti dışında karakter içeren bir şifre girilir.
4. Sign up butonuna tıklanır.

- **Beklenen Sonuç**

1. Kullanıcı şifre alanı için hata almalıdır.
