### ISSUE TITLE
[Devops]-Projenin development ortamınının hazırlanması.

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#36]

**Comment by muhammetduzenli** [comment]
Açılan issue kapsamında geliştirme ve test yapılacak ortam Azure Container Registry kullanılarak oluşturulmuştur.

Backend Link : https://survey-api.orangeground-88d990d8.westeurope.azurecontainerapps.io
Frontend Link : https://survey-ui.orangeground-88d990d8.westeurope.azurecontainerapps.io
