### ISSUE TITLE
[FillingOutSurvey]-Anket Doldurma Sayfasının Geliştirilmesi

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#5]
Ana sayfanın en alt kısmında uygulamada var olan anketler listelenmeli.Kullanıcı buradan istediği anketi seçip anketi doldurabilmedir.Seçtiği anket yeni bir sayfada açılmalıdır.

- [x]  Ankete ait sorunun bulunduğu bir alan (soru metni) olmalıdır. 

- [x]  Soruya ait seçenekler sorunun altında, alt alta (sorunun şıkları olarak düşünülebilir) listelenmelidir. 

- [x] Kullanıcı bu seçeneklerden yalnızca birini işaretleyebilmelidir.

- [x]  Kullanıcının anketi doldurması için giriş veya kayıt işlemi aranmamalıdır.

- [x]  Kullanıcının anketi tamamlayabilmesi için "Done" butonuna basması gerekmektedir. Butonun renk kodu #F27E97 olmalıdır. Yazının renk kodu #000000 olmalıdır. 

- [x] Kullanıcı giriş yapmamış ise anket cevabı kaydedilmeden önce giriş sayfasına yönlendirilmelidir.

- [ ]  Giriş yaptıktan sonra anket cevabı kaybolmamalı ve kaydedilmiş olmalıdır.

- [ ]  Giriş yapılmış ise kullanıcı tanınmalı ve giriş sayfasına yönlendirilmeden cevap kaydedilmelidir.

- [ ] Kullanıcı anketi tamamladıktan sonra örnek anketlerin listelendiği sayfaya (ana sayfanın en alt kısmında bulunan anket listesi) dönmelidir.

- [ ] Anket cevabı kaydedildikten sonra kullanıcı eğer aynı ankete tıklarsa daha önceden işaretlemiş olduğu seçenek
görünmelidir.

- [x] Kullanıcı dilerse eski yanıtını güncelleyebilmelidir.

 - [ ] #77

**Comment by esrayelmen** [comment]
## Test Senaryosu

### Homepage'deki "Surveys" alanının işlevselliği

- **Test Adımları**

1. Ana sayfaya git.
2. Ana sayfanın en alt kısmındaki Surveys alanına git.
3. Herhangi bir ankete tıkla. 

- **Beklenen Sonuç**

1. Seçilen anket yeni bir sayfada açılmalı.

### Anket doldurma sayfasınının düzeninin kontrolü

- **Test Adımları**

1. Sayfa düzenini incele.
2. Seçeneklere tıkla.

- **Beklenen Sonuç**

1. Üst kısımda ankete ait soru alanının bulunması.
2. Soru alanının altında soruya ait seçenekler alt alta bulunmalı.
3. Seçeneklerin sağ alt kısmında "Done" butonu bulunmalı. Butonu renk kodu #F27E97 olmalıdır. "Done" yazısının renk kodu #000000 olmalıdır.
4. Seçeneklerden yalnızca biri seçilebilmeli.

### Giriş yapmamış kullanıcı için "Done" butonunun işlevsellik kontrolü

- **Test Adımları**

1. Kullanıcı girişi yapmamış durumda ol.
2. Homepage/Surveys kısmından herhangi bir anket seç.
3. Seçeneklerden birini seç.
4. "Done" butonuna bas. 

- **Beklenen Sonuç**

1. Kullanıcı Login sayfasına yönlendirilmeli.
2. Cevap kaydedilmiş olmalı ve login olduktan sonra anket doldurma sayfasına geri dönülmeli.

### Giriş yapmış kullanıcı için "Done" butonunun işlevsellik kontrolü

- **Test Adımları**

1. Kullanıcı girişi yap.
2. Homepage/Surveys kısmından herhangi bir anket seç.
3. Seçeneklerden birini seç.
4. "Done" butonuna bas. 

- **Beklenen Sonuç**

1. Cevap kaydedilmeli ve ana sayfadaki örnek anketlerin listelendiği Surveys kısmına geri dönülmeli.

### Kaydedilen ankete tekrar tıklanması durumu

- **Test Adımları**

1. Kullanıcı girişi yap.
2. Homepage/Surveys kısmından herhangi bir anket seç.
3. Seçeneklerden birini seç.
4. "Done" butonuna bas. 
5. Aynı ankete tekrar tıkla.
6. Farklı bir seçenek seç.

- **Beklenen Sonuç**

1. Kullanıcı daha önce işaretlemiş olduğu seçeneği görebilmeli.
2. Kullanıcı isterse yanıtını güncelleyebilmelidir.
