### ISSUE TITLE
[Login]-Kullanıcı Girişinin Sağlanması

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#7]
Kullanıcı giriş yapmak istediğinde bu sayfaya yönlendirilmelidir.  Kullanıcı eğer giriş yapmadan anket oluşturma veya anket doldurma işlemini tamamladıysa bu işlem kaydedilmeden bu sayfaya yönlendirilmelidir.

- [x] Kullanıcı ana sayfa içerisindeki, üst barda bulunan,  'Login' seçeneği ile de giriş yapabilmelidir.

- [x] Kullanıcıdan,
          -  E-Mail
           -Şifre 
   bilgisi alınarak giriş yapması sağlanmalıdır. İlgili alanların içinde silik olarak "Enter your e-mail address" ve "Enter your 
   password" yazmalıdır. Kullanıcı bu alanı kullanmaya başladığında yazılar gider.

- [x]  Şifre ilk olarak gizli olarak yazılır. Kullanıcı şifreyi istediğinde görünür kılabilir ve tekrardan gizleyebilir.

- [x] #43

- [ ]  Kullanıcı yanlış E-mail veya şifre girmiş ise bunun hakkında uyarılmalıdır ve giriş sağlanmamalıdır.

- [x] Alt kısımda "Login" butonu bulunmalıdır. Yazı renginin kodu #FFFFFF ve butonun renk kodu #5380EA olmalıdır. 

- [x]  Login"butonunun altında "Don't have an account? Sign up" yazmalı ve kullanıcı buraya tıkladığında kayıt olma sayfasına yönlendirilmelidir.

- [ ]  Kullanıcı Login"butonuna tıkladığında giriş sağlanmış olmalıdır. Üst bardaki "Sign in" ve "Login" butonları gitmeli, yalnızca ikon kalmalıdır.

**Comment by esrayelmen** [comment]
## Test Senaryosu

### Login ekranındaki E-mail ve Şifre alanlarının özellikleri

- **Test Adımları**

1. E-mail ve Şifre alanlarının özelliklerini incele.
2. E-mail adresi gir.
3. Şifre gir.

- **Beklenen Sonuç**

1. E-mail alanında kullanıcı giriş yapmadan önce silik şekilde "Enter your e-mail address" yazması.
2. Şifre alanında kullanıcı giriş yapmadan önce silik şekilde "Enter your password" yazması.
3. Bilgi girişi yapıldıktan sonra silik yazıların kaybolması.

### Şifrenin görünürlük kontrolü

- **Test Adımları**

1. Şifre gir.
2. Şifre alanındaki ikona tıkla.
3. İkona tekrar tıkla.

- **Beklenen Sonuç**

1. Şifre ilk girildiğinde gizli olmalı. İkona tıklandığında görünür olmalı ve ikinci tıklamada tekrar gizli olmalı.

### Login butonunun bulunması ve özellikleri

- **Test Adımları**

1. Şifre alanının alt kısmını kontrol et.

- **Beklenen Sonuç**

1. Şifre alanının alt kısmında butonun bulunması. 
2. Butondaki "Log in" yazısının kodu #FFFFFF olmalı.
3. Butonun renk kodu #5380EA olmalı.

### Kullanıcının geçersiz e-mail adresi girmesi

- **Test Adımları**

1. Geçersiz bir e-mail adresi gir.
2. Geçerli bir şifre gir.
3. Login butonuna tıkla.

- **Beklenen Sonuç**

1. Kullanıcı sisteme giriş yapamamalı ve uyarı mesajı almalıdır.

### Kullanıcının geçersiz şifre girmesi

- **Test Adımları**

1. Geçerli bir e-mail adresi gir.
2. Geçersiz şifre gir.
3. Login butonuna tıkla.

- **Beklenen Sonuç**

1. Kullanıcı sisteme giriş yapamamalı ve uyarı mesajı almalıdır.

### Kullanıcının geçersiz e-mail ve şifre girmesi

- **Test Adımları**

1. Geçersiz bir e-mail adresi gir.
2. Geçersiz şifre gir.
3. Login butonuna tıkla.

- **Beklenen Sonuç**

1. Kullanıcı sisteme giriş yapamamalı ve uyarı mesajı almalıdır.

### Kullanıcının geçerli e-mail ve şifre girmesi

- **Test Adımları**

1. Geçerli bir e-mail adresi gir.
2. Geçerli bir şifre gir.
3. Login butonuna tıkla.

- **Beklenen Sonuç**

1. Kullancı sisteme giriş yapabilmeli.

### "Login" sayfasından "Registration" sayfasına yönlendirme yapılabilmesi

- **Test Adımları**

1. "Don't have an account? Sign up" yazısına tıkla.

- **Beklenen Sonuç**

1. Kullanıcı kayıt olma sayfasına yönlendirilmelidir.
