### ISSUE TITLE
[RatesOfSurveyResponses]-Ankete verilen cevapların oranlarının görüntülenmesi

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#76]
Kullanıcı, doldurduğu ankete daha önceden katılan kullanıcıların oy yüzdelerini görebilmeli.(Anket doldurma sayfası üzerinde.)

- [x] Kullanıcı anket doldurma ekranında anketini doldurup **"Done"** butonuna bastığında, ankete daha önceden katılan kullanıcılarının da oyları baz alınarak seçeneklerin yüzde olarak seçilme oranları şıklar üzerinde görünmelidir.

- [x] Kullanıcı oranları görmeden önce anketi tamamlaması gerektiği için hesabına giriş yapmış olması gerekmektedir.

- [x] Kullanıcı anket sorusunu ve seçenekleri görmeye devam etmelidir.

- [x] Yüzdeler seçeneklerin en sağında olacak şekilde konumlandırılmalıdır.

- [x] Seçeneklerin uzunluğu sahip olduğu yüzdelik orana göre değişmelidir.Örneğin en çok yüzdeliğe sahip seçenek en uzun seçenek olmalıdır. Diğer seçenekler de sahip oldukları yüzdelik oranlara göre boyutlandırılmalıdır.

- [x] Seçeneklerden en fazla yüzdeliğe sahip seçenek pembe (#E49192), anketteki diğer seçeneklerin yazılı olduğu alan ise gri renkte olmalıdır. (#616161)

- [ ] Kullanıcı anketini tamamladığı ve oranları görebildiği zaman sayfadan "Done" butonu kalkmalı haritaya yönlendirecek olan  **"See What The World Said"** butonu ve sayfayı scroll ettiğinde ulaşabildiği "Comment Section" kısmı kalmalıdır.

**Comment by ummugulsumm** [comment]
## Test Senaryosu

### Ankete verilen cevapların oranlarının görüntülenmesi kısmının incelenmesi 

- **Test Adımları**

1. Başarılı bir şekilde giriş yapılmalıdır. 
2. Anketlerin listelendiği sayfaya ulaşmak için üst bardan Surveys yazısına tıklanmalıdır.
3. Bir ankete tıklanmalıdır. 
4. Anket doldurmalıdır ve Done butonuna tıklanmalıdır.
5. Görüntü incelemesi yapılmalıdır.
6. Sayfa scroll edilmelidir. 

- **Beklenen Sonuç**

1. Giriş yapılmalıdır.
2. Anketlerin listelendiği kısma ulaşılmalıdır.
3. Anket doldurma sayfasına ulaşılmalıdır.
4. Seçeneklerin yüzde olarak seçilme oranları şıklar üzerinde görünmelidir. 
5. Yüzdeler seçeneklerin en sağında olacak şekilde konumlandırılmalıdır. Seçeneklerin uzunluğu sahip olduğu yüzdelik orana göre değişmelidir. Anket sorusu ve seçenekleri görünmeye devam etmelidir. Seçeneklerden en fazla yüzdeliğe sahip seçenek pembe (#E49192), anketteki diğer seçeneklerin yazılı olduğu alan ise gri renkte olmalıdır. (#616161) Sayfadan Done butonu kalkmalıdır. "See What The World Said" butonu kalmalıdır. 
6. Comment Section (yorum kısmına) ulaşılmalıdır.
