### ISSUE TITLE
[FilingOutSurvey]-Yeni tasarım güncellemeleri.

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#77]
- [x] Kullanıcının, ankete verilen popüler cevapları Dünya Haritası üzerinde görmesi için yönlendirme yapacak olan **"See The What World Said"** butonu bulunmalıdır
    - "Done" butonunun solunda 5380EA renkli boyutu 456x61 olan ovallik oranı %50, %90 opak, stroke ve bu stroke rengi 1B58E7, kalınlığı "1" ve efekt olarak Drop Shadow ve bu efektin özelliği %50 Blur 5380EA renk koduna sahip bir buton yer almaktadır.
   - Bu butonun içinde 87x107 boyutunda konumu ise x = 245 y = 791 olacak şekilde butonun içinde ve solunda olacak şekilde bir dünya ikonu yer alacaktır.
   - İkonun konumu = position: absolute;   width: 87px;   height: 107px;   left: 229px;    top: 783px;
   - Butonun konumu: x = 210 y = 814
   - Bu butonun içindeki yazı "See what the world said" yazması gerekmektedir.
   - "See what the world said" yazısının özellikleri:
	Yazı stili: Laila
	Yazı boyutu: 20
	Yazı rengi: 000000
	Yazı kalınlığı: Bold

- [x]  Anket doldurma sayfasının altında sol üst köşede header şeklinde **"Comments"** yazması gerekmektedir ve bu yazının altına **"Add comments"** butonu gelmektedir.
- "Add Comment" buton özellikleri:
	- Renk kodu: F0B80D
	- Yazı stili: Laila
	- Yazı boyutu: 19
	- Yazı kalınlığı: Bold
	- Yazı rengi: 000000
	- Butonun uzunluğu,genişliği ve ovallilik oranı: 200x36x%40
	- Butonun Sayfa içindeki konumu: x = 150 y = 1045

- [x] Sayfa scroll edilebilir olmalı, scrol edildiğinde kullanıcıların etkileşime geçtiği yorum sayfasını görebilmelidir.

**Comment by esrayelmen** [comment]
## Test Senaryosu

### "See What The World Said" butonunun özellikleri

- **Test Adımları**

1. Butonun tasarımsal özelliklerini incele.

- **Beklenen Sonuç**

1. "Done" butonunun solunda bulunmalı. Arka plan renk kodu "#5380EA" olmalıdır. Boyutu 456x61 ve ovallik oranı %50 olmalıdır. %90 opak ve kalınlığı "1" olmalıdır. Drop Shadow efekti olmalı ve bu efekt "#5380EA" renk kodunda %50 blurlu olmalıdır.
2. Butonun içinde ve solunda, konumu x=245 ve y =791 olacak şekilde 87x107 boyutunda dünya ikonu yer almalıdır.
3. İkonun konumu = position: absolute; width: 87px; height: 107px; left: 229px; top: 783px;
4. Butonun konumu: x = 210 y = 814
5. Butonun içinde Laila yazı stilinde, yazı boyutu 20, #000000 renk kodunda ve kalınlığı Bold olacak şekilde "See what the world said" yazmalıdır. 

### Comments alanının özellikleri

- **Test Adımları**

1. Alanın tasarımsal özelliklerini incele.

- **Beklenen Sonuç**

1. Anket doldurma alanının sol alt kısmında header şeklinde "Comments" yazmalıdır. 
2. Comments yazısının altında arka planı "#F0B80D"renk kodunda "Add comments" butonu bulunmalıdır.
3. Buton, 200x36 boyutunda olmalı ve %40 ovallik oranına sahip olmalıdır.
4. Butonun  sayfa içindeki konumu: x = 150 y = 1045
5. Butonun içindeki yazı Laila yazı stilinde, yazı boyutu 19, kalınlığı Bold, "#000000" renk kodunda olmalıdır. 

### Anket doldurma sayfasının scroll edilebilmesi

- **Test Adımları**

1. Sayfayı scroll et. 

- **Beklenen Sonuç**

1. Anket doldurma alanının alt kısmında bulunan yorum sayfası görülmelidir.
