### ISSUE TITLE
[Map]-Harita sayfasının tasarımsal özellikleri.

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#79]
- Harita tasarımı için örnek alınan siteyi inceleyebilirsiniz. [https://www.mapchart.net/world.html](url)

- [ ] Sayfanın ortasında yer alan mavi renkli ve oval olan şeklin özellikleri:

	Mavi renkli alanın kodu: 5380EA
	Mavi renkli alanın boyutu: 1440x856
	Mavi renkli alanın ovallik oranı : %400
	Mavi renkli alanın konumu: position; absolute ,  width; 1440px  , height; 856  , left; 8px  , top;256px

- [ ] Mavi alan içinde yer alan haritanın özellikleri ve konumu:
	Haritanın rengi: C5F0CF
	Haritadaki stroke rengi ve kalınlığı: 000000 (renk) 1 (kalınlık).
	Haritanın boyutu: 1285x769
	Haritanın konumu: left; 61px  ,  top; 279px

- [ ] Haritanın altında ve üstünde yatay bir şekilde konumlandırılmış "Scrollbar" yer almaktadır.

- [ ] Scrollbar'ın sağında ve solunda büyüktür küçüktür işaretlerini andıran 2 tane ikon yer almaktadır.

- Bu ikonlar karşılıklı olarak birbirine bakacak şekilde ayarlanmalıdır.
- İkonların özellikleri:
	Boyut: 22x16
	konumu: Scrollbar'a "29" birim uzaklıkta ve scrollbar'ı tam ortalaması gerekmektedir.

- [ ]  Dünya haritasının sağ alt köşesinde bir kare içerisinde "+" "-" ikonları alt alta gelecek şekilde yer almaktadır.

- Bu karenin boyutu: 31.2x60
- Bu "+" "-" ikonlarının boyutu: "+" ikonu için 18x18, "-" ikonu için 18.4x4

- [ ] Bu "+" "-" ikonlarına basıldığı zaman harita üstünde zoom in ve zoom out yapması gerekmektedir.

**Comment by MuhammedYurga** [comment]
[deneme.csv](https://github.com/bimser-intern/surveysaurus-pm/files/9547182/deneme.csv)
