### ISSUE TITLE
[AndroidRatesOfSurveyResponses]-Android uygulamada anket cevaplarının oranlarının görünmesi.

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#80]
Kullanıcı, doldurduğu ankete daha önceden katılan kullanıcıların oy yüzdelerini görebilmeli.(Anket doldurma sayfası üzerinde.)

- [x] Kullanıcı anket doldurma ekranında anketini doldurup **"Done"** butonuna bastığında, ankete daha önceden katılan kullanıcılarının da oyları baz alınarak seçeneklerin yüzde olarak seçilme oranları şıklar üzerinde görünmelidir.

- [x] Kullanıcı oranları görmeden önce anketi tamamlaması gerektiği için hesabına giriş yapmış olması gerekmektedir.

- [x] Kullanıcı anket sorusunu ve seçenekleri görmeye devam etmelidir.

- [x] Yüzdeler seçeneklerin en sağında olacak şekilde konumlandırılmalıdır.

- [x] Seçeneklerin uzunluğu sahip olduğu yüzdelik orana göre değişmelidir.Örneğin en çok yüzdeliğe sahip seçenek en uzun seçenek olmalıdır. Diğer seçenekler de sahip oldukları yüzdelik oranlara göre boyutlandırılmalıdır.

- [x] Seçeneklerden en fazla yüzdeliğe sahip seçenek pembe (#E49192), anketteki diğer seçeneklerin yazılı olduğu alan ise gri renkte olmalıdır. (#616161)

- [x] Kullanıcı anketini tamamladığı ve oranları görebildiği zaman sayfadan "Done" butonu kalkmalı yorum sayfasına yönlendiren **"Add Comment"** butonu, haritaya yönlendirecek olan  **"See What The World Said"** butonu ve sayfanın en altında bulunan ve kullanıcıyı yorumların olduğu sayfaya götürecek olan yazı (**Swipe Up To See Comments**) bulunmalıdır.

**Comment by ummugulsumm** [comment]
## Test Senaryosu

### Ankete verilen cevapların oranlarının görüntülenmesi kısmının incelenmesi 

- **Test Adımları**

1. Başarılı bir şekilde giriş yapılmalıdır. 
2. Anketlerin listelendiği sayfaya ulaşmak için ana sayfa sola kaydırılmalıdır.
3. Bir ankete tıklanmalıdır. 
4. Anket doldurmalıdır ve Done butonuna tıklanmalıdır.
5. Görüntü incelemesi yapılmalıdır.
6. Add comment butonuna tıklanmalıdır.
7. Anket doldurma sayfasına tekrar dönüp sayfa kaydırılmalıdır.
8. Anket doldurma sayfasına tekrar dönüp See What The World Said butonuna tıklanmalıdır.

- **Beklenen Sonuç**

1. Giriş yapılmalıdır.
2. Anketlerin listelendiği kısma ulaşılmalıdır.
3. Anket doldurma sayfasına ulaşılmalıdır.
4. Seçeneklerin yüzde olarak seçilme oranları şıklar üzerinde görünmelidir. 
5. Yüzdeler seçeneklerin en sağında olacak şekilde konumlandırılmalıdır. Seçeneklerin uzunluğu sahip olduğu yüzdelik orana göre değişmelidir. Anket sorusu ve seçenekleri görünmeye devam etmelidir. Seçeneklerden en fazla yüzdeliğe sahip seçenek pembe (#E49192), anketteki diğer seçeneklerin yazılı olduğu alan ise gri renkte olmalıdır. (#616161) Sayfadan Done butonu kalkmalıdır. Done butonu yerinde "Add Comment" butonu olmalıdır. Onun altında "See What The World Said" butonu olmalıdır.  Sayfanın en altında "Swipe up to see comments" yazısı olmalıdır. 
6. Yorumların olduğu kısma yönlendirmelidir. 
7. Yorumların olduğu kısma yönlendirmelidir. 
8. Map sayfasına yönlendirmelidir.
