### ISSUE TITLE
[CommentSection]-Kullanıcı girdiği anket altında yorum yapabilmelidir.

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#84]
Anket doldurma sayfası scroll edildiğinde kullanıcının yorum yapabildiği, diğer kullanıcıların da yorumlarını okuyup etkileşim haline geçebileceği  sayfa.

- [x] Kullanıcı hesabına giriş yapmamış olsa dahi girdiği anketin altında bulunan yorumları okuyabilmelidir.

- [x]  Kullanıcı anket doldurma sayfasının altında sol üst köşede header şeklinde "Comments" yazması gerekmektedir ve bu yazının altına "Add comments" butonu gelmektedir.

- [x]  Kullanıcının yorumunu paylaşabilmesi için hesabına giriş yapması gerekmektedir.

- [x]  Kullanıcı yorumunu paylaştığı an sayfa yenilenmesine gerek kalmadan yorumunu görebilmelidir.

- [x] Oturum açmayan bir kullanıcı, yorumları okuyabilir ve text alanına yorum yazabilir ancak yorumu paylaşmak için "comment" butonuna bastığında kullanıcı girişi istenmelidir.

- [x] Hesabı olmayan veya oturum açmayan kullanıcı yorum yapmak istediğinde "Comment" butonuna basınca ekrana "Login" sayfası açılması gerekmektedir. Giriş yaptıktan sonra yorumununu sitede paylaşabilmelidir.  

- [x] Kullanıcı yazdığı yorumları silebilmelidir.

- [x] Yorumlar 24 saati geçmemişse saat cinsinden yazılmalıdır(8hr.), 24 saati geçmişse ve bir haftayı doldurmamışsa gün cinsinden(4d), 1 haftayı doldurur ve geçerse hafta cinsinden(1w, 2w) gözükmelidir. 
  
- [x] Her kullanıcının yorum kısmında kullanıcı adının baş harfinin bulunduğu ikonu olması zorunludur 

- [x] #85

**Comment by SimgeTerzioglu** [comment]
## Test Senaryosu

### Giriş yapılmadan anket yorumlarına erişebilme durumu

- **Test Adımları**

1. Siteye gelinir.
2. Anket doldurma sayfasına gelinir.
3. Yorumlar kısmı kontrol edilir.

- **Beklenen Sonuç**

1. Kullanıcı yorumları görüntüleyebilmelidir.

### "Comments" yazısı ve "Add Comment" butonu kontrolü

- **Test Adımları** 

1. Siteye gelinir.
2. Anket doldurma sayfasına gelinir.
3. "Comments" alanı kontrol edilir.
4. "Add Comment" butonu kontrol edilir.

- **Beklenen Sonuç**

1. Anket doldurma sayfasının altında sol üst köşede header şeklinde "Comments" yazısı bulunmalıdır.
2. "Comments" yazsının altında "Add Comment" butonu bulunmalıdır.

### Giriş yapılmadan yorum paylaşabilme durumu

- **Test Adımları**

1. Siteye gelinir.
2. Anket doldurma sayfasına gelinir.
3. Yorum alanına yazı yazılır.
4. "Comment" butonuna basılır.

- **Beklenen Sonuç**

1. Kullanıcının yorum alanına yorum yazabiliyor olması gerekir.
2. Kullanıcı "Comment" butonuna tıklandığında login sayfasına yönlendirilmelidir.
3. Kullanıcı giriş işlemini tamamladığında yorumu paylaşılmalıdır.

### Giriş yapılarak yorum paylaşabilme durumu

- **Test Adımları**

1. Siteye giriş yapılır.
2. Anket doldurma sayfasına gelinir.
3. Yorum alanına yazı yazılır.
4. "Comment" butonuna basılır.

- **Beklenen Sonuç**

1. Kullanıcının yorum alanına yorum yazabiliyor olması gerekir.
2. Kullanıcı "Comment" butonuna tıkladığında yorumu paylaşılmalıdır.
3. Kullanıcı sayfa yenilenmeden yorumunu yorumlar kısmında görüntüleyebilmelidir.

### Kullanıcının kendi paylaştığı yorumu silmesi durumu

- **Test Adımları**

1. Siteye giriş yapılır.
2. Anket doldurma sayfasına gelinir.
3. Kullanıcın kendi paylaşmış olduğu yorum silinir.

- **Beklenen Sonuç**

1. Silinen yorum yorumlar sayfasından kaldırılmalıdır.

### Paylaşılan yorumlardaki kullanıcı ikonu durumu

- **Test Adımları**

1. Anket doldurma sayfasına gelinir.
2. Kullanıcı ikonları kontrol edilir.

- **Beklenen Sonuç**

1. Paylaşılan yorumlarda kullanıcı ikonu ve kullanıcı ikonunun içinde kullanıcı adının baş harfleri olmalıdır.

### Yorumların paylaşıldığı zamanın gösterilme durumu

- **Test Adımları**

1. Anket doldurma sayfasına gelinir.
2. Yorumlar kısmında yorumların yapılma zamanları kontrol edilir.

- **Beklenen Sonuç**

1. Yorumlar 24 saati geçmemişse saat cinsinden yazılmalıdır(8hr.), 24 saati geçmişse ve bir haftayı doldurmamışsa gün cinsinden(4d), 1 haftayı doldurur ve geçerse hafta cinsinden(1w, 2w) gözükmelidir.
