### ISSUE TITLE
[CommentSection]-Yorumlar bir alan içerisine yazılacak, bu alanın açılması için kişinin "Add Comment" butonuna basması gerekmektedir.

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#85]
Login yapmış bir kullanıcıya yorum sayfasında sol üst köşedeki "Add Comment" butonuna basınca yorum yapmasına olanak tanıyan bir alan.

- [x] Kullanıcının yorumunu yazabileceği bir text alanı bulunmalıdır.

- [x] Alanın içinde silik bir şekilde "What Are Your Toughts?" yazmalı ve yorum yazılmaya başlayınca yazı silinmelidir.

- [x] #92

- [x] Sağ altta bulunan "Comment" butonu ile kullanıcı yorumunu paylaşabilecektir. Bu butona bastıktan sonra yorum sayfasına dönmesi beklenmektedir.

**Comment by SimgeTerzioglu** [comment]
## Test Senaryosu

### Yorum yazma alanının varlığı

- **Test Adımları**

1. Siteye gelinir.
2. Anket doldurma sayfasına tıklanır.
3. Yorum yazma alanı kontrol edillir.

- **Beklenen Sonuç**

1. Yorumların altında yorum yazma alanı bulunmalıdır.

### "What are your thoughts?" yazısının kontrolü

- **Test Adımları**

1. Siteye gelinir.
2. Anket doldurma sayfasına tıklanır.
3. Yorum yazma alanı kontrol edillir.

- **Beklenen Sonuç**

1. Silik bir şekilde "What are your thoughts?" yazıyor olmalıdır.

### "Comment" butonu kontrolü

- **Test Adımları**

1. Siteye gelinir.
2. Anket doldurma sayfasına tıklanır.
3. "Comment" butonu kontrol edilir.

- **Beklenen Sonuç**

1. Buton sağ alt köşede bulunmalıdır.

### "Comment" butonunun işlevsellik kontrolü 

- **Test Adımları**

1. Siteye gelinir.
2. Anket doldurma sayfasına tıklanır.
3. Yorum yazılır.
4.  "Comment" butonuna tıklanır.

- **Beklenen Sonuç**

1. Yazılan yorum paylaşılmalıdır ve kullanıcı yorumlar sayfasında kalmalıdır.
